[package]
name = "fffc"
version = "0.1.0"
edition = "2021"
authors = ["Spencer M. Chunn <smchunn@icloud.com>"]

[dependencies]
uuid = { version = "1", features = ["serde", "v4"] }
csv = "1"
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "fffc"
path = "fffc.rs"


